### ISSUE TITLE
TODO =>

### ISSUE THREAD

**Issue by RusHiiii** [RusHiiii/fldamiens#1]
https://profile-readme-generator.com/

**Comment by RusHiiii** [comment]
- [ ] CI (cp image)
- [ ] date en année (date fin - date début = nb année + nb mois)
- [ ] experience endedAt nullable côte react admin à faire
- [ ] readme github
- [ ] dump et save config file

**Comment by RusHiiii** [comment]
https://www.flaticon.com/search?author_id=1&style_id=&type=standard&word=
